name: agriwise1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  provider: ^6.0.2
  flutter_bloc: ^8.1.3
  flutter_tts: ^4.2.2
  fl_chart: ^0.66.0
  image_picker: ^1.1.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.6
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  equatable: ^2.0.5
  get_it: ^7.6.4
  weather: ^3.1.1
  geolocator: ^10.1.0
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/crop_health.json
